# NLP Group 08 Project

# NLP-Based Customer Support Ticket Classification System

### Notebook 3:  Feature Engineering

**Course:** 7500 - Natural Language Processing  
**Group:** 08

---

## Objective

The purpose of this notebook is to explore different types of Featuring Engineering that can be used while testing various models in the next notebook.  

This includes:
- TF-IDF for classification models
- BoW for classification models

## Imports

In [6]:
import pandas as pd
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

Retrieve pre-processed training data

In [2]:
train_df = pd.read_csv("../data/nlp_dataset_train_pre-processed.csv")

## Set TF-IDF function using sklearn

Function TF_IDF(df, text):
- Inputs
  - df = df containing the text to process;
  - text = reference to text containing column.
- Initalizes the vectorizer
- applies the vectorizer to the input text
- creates a dataframe from the resulting output, with extracted feature names are used for the column headers
- merges the new TF-IDF data frame back into the original dataframe.

In [15]:
def TF_IDF(df, text):
    df = df
    text = text
    
    tfidf_vectorizer = TfidfVectorizer(stop_words = 'english', smooth_idf = True, norm = 'l2')
    tfidf_vector = tfidf_vectorizer.fit_transform(text)
    feature_names = tfidf_vectorizer.get_feature_names_out()
    
    tfidf_df = pd.DataFrame(tfidf_vector.toarray(), columns = feature_names)
    tfidf_df = df.join(tfidf_df, how = 'outer')
    return tfidf_df

Apply the function to the training dataset

In [16]:
#Function Testing on Training Set
df = train_df
text = train_df['Combined Text']
tfidf_df = TF_IDF(df, text)
tfidf_df.head(6)

,Unnamed: 0,Customer Email,Product Purchased,Ticket Type,Ticket Subject,Combined Text,Ticket Priority,ab,ability,able,...,zee,zendesk,zero,zerohits,zilp,zip,zoe,zoltan,zombii,zoom
0,2794,jessica95@example.com,dell xps,cancellation request,peripheral compatibility,dell xps making strange noise functioning prop...,medium,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7497,elizabethmeadows@example.com,philips hue lights,cancellation request,delivery problem,issue philip hue lights please assist product ...,critical,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7646,foxrichard@example.com,canon dslr camera,billing inquiry,hardware issue,forgotten password canon dslr camera account p...,high,0.0,0.0,0.151363,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2726,christinahicks@example.com,microsoft surface,product inquiry,payment issue,issue microsoft surface please assist for exam...,medium,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4348,palmersamuel@example.com,iphone,refund request,hardware issue,issue iphone please assist otherwise match exi...,low,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,3753,elizabeth82@example.net,adobe photoshop,technical issue,cancellation request,recently set adobe photoshop fails connect ava...,high,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Set BoW Function using sklearn

Function BoW(df, text):
- Inputs
  - df = df containing the text to process;
  - text = reference to text containing column.
- Initalizes the vectorizer
- applies the vectorizer to the input text
- creates a dataframe from the resulting output
- merges the new BoW data frame back into the original dataframe

In [19]:
def BoW(df, text):
    df = df
    text = text

    bow_vectorizer = CountVectorizer()
    bow_vector = bow_vectorizer.fit_transform(text)
    feature_names = bow_vectorizer.get_feature_names_out()

    bow_df = pd.DataFrame(bow_vector.toarray(), columns=feature_names)
    bow_df = df.join(bow_df, how = 'outer')
    return bow_df

Apply the function to the training dataset

In [20]:
#Function Testing on Training Set
df = train_df
text = train_df['Combined Text']
bow_df = BoW(df, text)
bow_df.head(6)

,Unnamed: 0,Customer Email,Product Purchased,Ticket Type,Ticket Subject,Combined Text,Ticket Priority,ab,ability,able,...,zee,zendesk,zero,zerohits,zilp,zip,zoe,zoltan,zombii,zoom
0,2794,jessica95@example.com,dell xps,cancellation request,peripheral compatibility,dell xps making strange noise functioning prop...,medium,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7497,elizabethmeadows@example.com,philips hue lights,cancellation request,delivery problem,issue philip hue lights please assist product ...,critical,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,7646,foxrichard@example.com,canon dslr camera,billing inquiry,hardware issue,forgotten password canon dslr camera account p...,high,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2726,christinahicks@example.com,microsoft surface,product inquiry,payment issue,issue microsoft surface please assist for exam...,medium,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4348,palmersamuel@example.com,iphone,refund request,hardware issue,issue iphone please assist otherwise match exi...,low,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,3753,elizabeth82@example.net,adobe photoshop,technical issue,cancellation request,recently set adobe photoshop fails connect ava...,high,0,0,0,...,0,0,0,0,0,0,0,0,0,0